title: Josh Brigden
baseline: A-Level Photography Student
description: Blog to support my Sketchbook work and act as a journal for it.
baseurl: /
canonicalurl: true
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/London
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
